service: meetup-backend-api

provider:
    name: aws
    runtime: nodejs18.x
    region: eu-north-1
    environment:
        USERS_TABLE: Meetup-Users
        MEETUPS_TABLE: Meetups
    iamRoleStatements:
        - Effect: 'Allow'
          Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:Scan
              - dynamodb:Query
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
              - dynamodb:DescribeTable
          Resource:
              - arn:aws:dynamodb:eu-north-1:*:table/Meetup-Users
              - arn:aws:dynamodb:eu-north-1:*:table/Meetup-Users/index/EmailIndex
              - arn:aws:dynamodb:eu-north-1:*:table/Meetups

functions:
    createAccount:
        handler: functions/createAccount.handler
        events:
            - http:
                  path: users/createAccount
                  method: post

    loginAccount:
        handler: functions/loginAccount.handler
        events:
            - http:
                  path: users/loginAccount
                  method: post

    getAllUsers:
        handler: functions/getAllUsers.handler
        events:
            - http:
                  path: users
                  method: get

    createMeetup:
        handler: functions/createMeetup.handler
        events:
            - http:
                  path: meetups
                  method: post

    getAllMeetups:
        handler: functions/getAllMeetups.handler
        events:
            - http:
                  path: meetups
                  method: get

    registerForMeetup:
        handler: functions/registerForMeetup.handler
        events:
            - http:
                  path: meetups/{meetupId}/register
                  method: post

    getMeetupInfoById:
        handler: functions/getMeetupInfoById.handler
        events:
            - http:
                  path: meetups/{meetupId}
                  method: get

    getMeetupByKeyword:
        handler: functions/getMeetupByKeyword.handler
        events:
            - http:
                  path: meetups/search
                  method: get
                  request:
                      parameters:
                          querystrings:
                              keyword: true

    cancelMeetup:
        handler: functions/cancelMeetup.handler
        events:
            - http:
                  path: meetups/cancel
                  method: post

    myProfile:
        handler: functions/myProfile.handler
        events:
            - http:
                  path: users/profile
                  method: get
                  request:
                      parameters:
                          querystrings:
                              userId: true
