name: Deploy to S3 (Dev Environment)

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: Frontend
        run: npm install

      - name: Build project
        working-directory: Frontend
        run: npm run build

      - name: Install or Update AWS CLI
        run: |
          if ! command -v aws &> /dev/null; then
            echo "AWS CLI is not installed. Installing..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
          else
            echo "AWS CLI is already installed. Updating..."
            sudo ./aws/install --update
          fi

      - name: Deploy to S3 Dev
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_DEV }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync Frontend/dist/ s3://$AWS_S3_BUCKET --delete
